name: Build Release Bundle
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV


      - name: Decode Keystore
        id: decode-keystore
        run: |
          mkdir -p ./keystore/
          echo -n "${{ secrets.KEYSTORE }}" | base64 -d > ./keystore/keys.jks
          echo -ne "SIGNING_KEYSTORE_PATH=${{ secrets.SIGNING_KEYSTORE_PATH }}" >> ./secret.properties
          echo -ne "\nSIGNING_STORE_PASSWORD=${{ secrets.SIGNING_STORE_PASSWORD }}" >> ./secret.properties
          echo -ne "\nSIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}" >> ./secret.properties

      - name: Extract Google Services JSON
        id: extract-google-services
        run: |
          echo -n "${{ secrets.GOOGLE_SERVICES }}" | base64 -d > ./app/google-services.json

      - name: Create sentry.properties
        id: create-sentry-properties
        run: |
          echo -ne "defaults.org=${{ secrets.SENTRY_ORG }}" >> ./sentry.properties
          echo -ne "\ndefaults.project=${{ secrets.SENTRY_PROJECT }}" >> ./sentry.properties
          echo -ne "\nauth.token=${{ secrets.SENTRY_AUTH_TOKEN }}" >> ./sentry.properties

      - name: Set version code
        run: |
          echo -ne "\nVERSION_CODE=${{ github.run_number }}" >> ./version.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release Bundle
        run: ./gradlew app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/
